version: '3'
services:
  cme-ctc-web:
    build: Commitment_to_Change_App/
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      # General policy: unless the app SHOULD write to a dir, it should be RO.
      # For Django, only migrations dirs should have write permissions.
      # Since we presently don't commit them or really care what's in them,
      # but do need them to persist with the container, they are volumes.
      # For testing, pytest and coverage both need to write somewhere, but since
      # we currently don't use those files directly, make them volumes too.
      - ./Commitment_to_Change_App:/app
    depends_on:
      - cme-ctc-db
      - cme-ctc-mailcapture

  cme-ctc-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Insecure7

  cme-ctc-mailcapture:
    build: mailcapture/
    command: aiosmtpd -l 0.0.0.0:25 -c aiosmtpd.handlers.Debugging
    stop_signal: SIGINT
    environment:
      PYTHONUNBUFFERED: 1

