name: Test main Django site
on:
  pull_request:
    branches:
      - master

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Commitment_to_Change_App/requirements.txt

      - name: Create custom_settings.py
        working-directory: ./Commitment_to_Change_App/Commitment_to_Change_App
        run: cat custom_settings_default.py | sed "s/''/'$(python -c "import secrets; print(secrets.token_urlsafe())")'/" > custom_settings.py

      - name: Run pytest
        working-directory: ./Commitment_to_Change_App
        run: pytest -vv
