name: Test main Django site
on:
  pull_request:
    branches:
      - master

jobs:
  pytest:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Commitment_to_Change_App/requirements.txt

      - name: Create custom_settings.py
        working-directory: ./Commitment_to_Change_App/Commitment_to_Change_App
        run: cat custom_settings_sources/custom_settings_github.py | sed "s/SECRET_KEY = ''/SECRET_KEY = '$(python -c "import secrets; print(secrets.token_urlsafe())")'/" > custom_settings.py

      - name: Overwrite test settings
        run: export DJANGO_SETTINGS_MODULE="Commitment_to_Change_App.settings"

      - name: Migrate
        working-directory: ./Commitment_to_Change_App
        run: |
          python manage.py makemigrations 
          python manage.py migrate

      - name: Run pytest
        working-directory: ./Commitment_to_Change_App
        run: pytest -vv
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Commitment_to_Change_App/requirements.txt

      - name: Create custom_settings.py
        working-directory: ./Commitment_to_Change_App/Commitment_to_Change_App
        run: cat custom_settings_sources/custom_settings_github.py | sed "s/SECRET_KEY = ''/SECRET_KEY = '$(python -c "import secrets; print(secrets.token_urlsafe())")'/" > custom_settings.py

      - name: Overwrite test settings
        run: export DJANGO_SETTINGS_MODULE="Commitment_to_Change_App.settings"

      - name: Run djlint for errors
        working-directory: ./Commitment_to_Change_App
        run: djlint --profile=django .
